name: TownyPermissions
version: '1.0-SNAPSHOT'
main: org.dexterx.mc.townypermissions.TownyPermissions
api-version: '1.20'
depend: [Towny, LuckPerms]
authors: [DexterX]
description: Permissions per Towny

commands:
  tperm:
    description: Manage permissions per town
    usage: /tperm <Town> <add|remove> <permission>
    permission: townypermissions.manage
    permission-message: You don't have permission to use this command.